version: '3.8'

services:
  file-manager:
    build: .
    image: file-manager-api:latest
    container_name: file-manager-api
    ports:
      - "3000:3000"
    volumes:
      - /data/heygemdata:/app/storage
    environment:
      - PORT=3000
      - STORAGE_PATH=/app/storage